Handle empty issue body when removing HTML
instantish/notion-github-action pull request #30
Opened 2021-09-28 14:41 UTC by conarro

If an issue is created with an empty body, the action failed when calling `replace` on `null`. This PR updates the `removeHTML` function to return an empty string if the `text` argument is `null`.

2021-09-28 15:51 UTC, rr-codes requested changes

2021-09-28 15:51 UTC, rr-codes commented on src/action.ts
>  function removeHTML(text: string): string {
```suggestion
function removeHTML(text?: string): string {
```

2021-09-28 15:52 UTC, rr-codes commented
Thanks @conarro! I added a few comments. Would you also mind creating a corresponding issue for this as well please? Thanks!

2021-09-28 17:19 UTC, conarro commented
@rr-codes filed an issue here #31. Just applied your suggestions, let me know if you want me to squash or anything!

2021-09-30 19:04 UTC, marissamarym approved these changes
LGTM

2021-09-30 20:17 UTC, merged